export enum ROLE_ENUM {
  ADMIN = 'admin',
  USER = 'user',
}

export enum GENDER_ENUM {
  MALE = 'male',
  FEMALE = 'female',
}

export enum STATUS_ENUM {
  PENDING = 'PENDING',
  COMPLETE = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export const DB = {
  USERFULL: 'user-full',
  USER: 'user',
  SHIFT: 'shift',
  SIGNUP: 'signup',
  FORGOTPASSWORD: 'forgot-password',
  RESETPASSWORD: 'reset-password',
  VERIFYOTP: 'verifyOTP',
  ASSIGNSHIFT: 'assignedshift',
  DEPARTMENTCATEGORY: 'department-cat',
  DEPARTMENT: 'department',
  DEPARTMENTSUBCAT: 'depa-subcat',
  LABTEST: 'labtest',
  LABORATORY: 'laboratory',
  LABORATORYREPORT: 'laboratoryReport',
  HOSPITAL: 'hospital',
  SYSTEMSETTING: 'systemsetting',
  PRINTERSETTING: 'printersetting',
  FINGERPRINT: 'fingerprint',
  TOKEN: 'token',
  ATTENDANCE: 'attendance',
  PERMISSION: 'permission',
  OPERATIONTHEATRES: 'operation-theatre',
  OPERATIONTHEATRE: 'ot-assignment',
  HOSPITALPRODUCT: 'hproduct',
  WARDCAT: 'ward-category',
  WARDCATEGORY: 'sub-ward-category',
  ROOMMODEL: 'room',
  BEDASSIGN: 'assignbed',
  SERVICECATEGORY: 'servicecat',
  TREATMENTSERVICE: 'tratmentservice',
  APPOINTMENT: 'appointment',
  BANK: 'bank',
  BANKTRANSACTION: 'banktransaction',
  FINANCIALTRANSACTION: 'financialtransaction',
  PATIENTHISTORY: 'patienthistory',
  SYMPTOMS: 'symptoms',
  ALLERGY: 'allergy',
  CHRONICDISEASE: 'chronicdisease',
  MEDICALPRODUCT: 'medicalproduct',
  MEDICALPRODUCTINVENTORY: 'medicalInventory',
  SALEPURCHASE: 'salepurchase',
  AMBULANCELIST: 'ambulance',
  AMBULANCETYPE: 'ambulance-conf',
  AMBULANCEINQUIRY: 'ambulance-inquiry',
  CANTEENPRODUCT: 'cproduct',
  CANTEENINVENTORY: 'c-inventory',
  HOSPITALINVENTORY: 'h-inventory',
  HOSPITALINVENTORYPRODUCT: 'hproduct',
  HOSPITALINVENTORYPRODUCTCATEGORY: 'hproductcat',
  PAYROLLCONFIGALLOWANCE: 'allowance',
  PAYROLLCONFIGDEDUCTION: 'deduction',
  PAYROLLSALARY: 'salary',

  CERTIFICATE: 'certificate',
  INVOICE: 'invoice',
  TESTCONFIG: 'lab-test',
  TRANSATIONADJUSTMENT: 'transaction-adjustment',
  FINANCETRANSACTION: 'financial-transaction',
  TRANSACTION: 'transactions',
  JOB: 'job',
  JOBAPPLICATION: 'career',
  BOD: 'bod',
};

export const userRole = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  ADMINISTRATION: 'ADMINISTRATION',
  DOCTOR: 'DOCTOR',
  MEDICAL_OFFICER: 'MEDICAL_OFFICER', //doctor//
  CONSULTANT: 'CONSULTANT', //doctor//
  NURSE: 'NURSE',
  PATIENT: 'PATIENT',
  PHARMACIST: 'PHARMACIST',
  STAFF: 'STAFF',

  PATHOLOGIST: 'PATHOLOGIST', //lab//
  LAB_TECHNOLOGIST: 'LAB_TECHNOLOGIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  OTHER: 'OTHER',
  VENDOR: 'VENDOR',
  RECEPTIONIST: 'RECEPTIONIST',
  RESELLER: 'RESELLER',
  PHYSIOTHERAPIST: 'PHYSIOTHERAPIST', //doctor//
  RADIOLOGIST: 'RADIOLOGIST',
  SURGEON: 'SURGEON', //doctor//
  ANESTHESIOLOGIST: 'ANESTHESIOLOGIST', //doctor//
  DENTIST: 'DENTIST', //doctor//
  OPTOMETRIST: 'OPTOMETRIST', //doctor//
  DIETICIAN: 'DIETICIAN', //nurse
  PSYCHOLOGIST: 'PSYCHOLOGIST', //doctor//
  SOCIAL_WORKER: 'SOCIAL_WORKER',
  HOSPITAL_MANAGER: 'HOSPITAL_MANAGER',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  ASSISTANT_MANAGER: 'ASSISTANT_MANAGER',
  ASSISTANT_ACCOUNTANT: 'ASSISTANT_ACCOUNTANT',

  IT_OFFICER: 'IT_OFFICER',
  SUPERVISOR: 'SUPERVISOR',
  CLEANER: 'CLEANER',
  SECURITY_GUARD: 'SECURITY_GUARD',
  OFFICE_BOY: 'OFFICE_BOY',
  ELECTRICIAN: 'ELECTRICIAN',
  DRIVER: 'DRIVER',
  PHARMACIST_ASSISTANT: 'PHARMACIST_ASSISTANT',
  PLUMBER: 'PLUMBER',
};

export const TokenStatus = {
  queue: 'IN-QUE',
  running: 'RUNNING',
  completed: 'COMPLETED',
  cancel: 'CANCEL',
};

export const ProductCategory = {
  DRUG: 'DRUG',
  MEDICALSUPPLIES: 'MEDICAL-SUPPLIES',
  DEVICES: 'DEVICES',
  PERSONALCARETOILETRIES: 'PERSONALCARE-TOILETRIES',
  LIFESTYLEPRODUCT: 'LIFESTYLE-PRODUCT',
  BEAUTIESSKINCARE: 'BEAUTIES-SKIN-CARE',
  LABTEST: 'LAB-TEST',
  OTHER: 'OTHER',
};

export const SALARYTYPE = {
  PERHOUR: 'PERHOUR',
  PERPATIENT: 'PERPATIENT',
  PERDAY: 'PERDAY',
  PERSHIFT: 'PERSHIFT',
  PERMONTH: 'PERMONTH',
};

export const DietType = {
  REGULAR: 'REGULAR',
  SOFT: 'SOFT',
  PUREED: 'PUREED',
  LIQUID: 'LIQUID',
  CLEAR_LIQUID: 'CLEAR_LIQUID',
  LOW_SODIUM: 'LOW_SODIUM',
  LOW_FAT: 'LOW_FAT',
  DIABETIC: 'DIABETIC',
  RENAL: 'RENAL',
  CARDIAC: 'CARDIAC',
  HIGH_PROTEIN: 'HIGH_PROTEIN',
  LOW_RESIDUE: 'LOW_RESIDUE',
  GLUTEN_FREE: 'GLUTEN_FREE',
  LACTOSE_FREE: 'LACTOSE_FREE',
  VEGETARIAN: 'VEGETARIAN',
  VEGAN: 'VEGAN',
  KETO: 'KETO',
};

export const DESIGNATIONENUM = {
  HOD: 'HOD',
  SENIOR: 'SENIOR',
  INTERMEDIATE: 'INTERMEDIATE',
  JUNIOR: 'JUNIOR',
  ASSISTANT: 'ASSISTANT',
  INTERN: 'INTERN',
};
export const paymentMethod = {
  cash: 'CASH',
  bank: 'BANK',
  cheque: 'CHEQUE',
};
export const paymentStatus = {
  paid: 'PAID',
  pending: 'PENDING',
  PARTIALLYPAID: 'PARTIALLY-PAID',
  REJECTED: 'REJECTED',
};
export const INVENTROYENUM = {
  HOSPITAL: 'HOSPITAL',
  LABORATORY: 'LABORATORY',
  CANTEEN: 'CANTEEN',
  PHARMACY: 'PHARMACY',
  RADIOLOGY: 'RADIOLOGY',
};

export const SALEPURCHASEENUM = {
  SALE: 'SALE',
  PURCHASE: 'PURCHASE',
  RETURN: 'RETURN',
  SALERETURN: 'SALERETURN',
  SAMPLE: 'SAMPLE',
  DISPATCH: 'DISPATCH',
  OLDSTOCK: 'OLDSTOCK',
};
export const PAYMENTSTATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PARTPAID: 'PARTIALLY-PAID',
};
export const PARAMETERSTATUS = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  INFANT: 'INFANT',
  CHILD: 'CHILD',
};

export const PACKAGINGENUM = {
  BOX: 'BOX',
  BOTTLE: 'BOTTLE',
  STRIP: 'STRIP',
  VIAL: 'VIAL',
  OTHER: 'OTHER',
};

export const FORMENUM = {
  TABLET: 'TABLET',
  INJECTION: 'INJECTION',
  LIQUID: 'LIQUID',
  CREAM: 'CREAM',
  GEL: 'GEL',
  POWDER: 'POWDER',
  OTHER: 'OTHER',
};

export const ROUTEENUM = {
  ORAL: 'ORAL',
  INJECTION: 'INJECTION',
  TOPICAL: 'TOPICAL',
  INHALATION: 'INHALATION',
  OTHER: 'OTHER',
};

export const SKINCARECATEGORYENUM = {
  CLEANSER: 'CLEANSER',
  MOISTURIZER: 'MOISTURIZER',
  SERUM: 'SERUM',
  TONER: 'TONER',
  SUNSCREEN: 'SUNSCREEN',
  MASK: 'MASK',
  EXFOLIATOR: 'EXFOLIATOR',
  LIPCARE: 'LIP-CARE',
  EYECREAM: 'EYE-CREAM',
  BODYLOTION: 'BODY-LOTION',
  OTHER: 'OTHER',
};

export const LABTESTCATEGORYENUM = {
  ANALYSER: 'ANALYSER',
  CENTRIFUSE: 'CENTRIFUSE',
  MICROSCOPE: 'MICROSCOPE',
  INCUBATOR: 'INCUBATOR',
  SPECTROPHOTOMETER: 'SPECTROPHOTOMETER',
  OTHER: 'OTHER',
};

export const REPORTSTATUS = {
  PENDING: 'PENDING',

  SAMPLECOLLECTED: 'SAMPLE-COLLECTED',
  REPORTED: 'REPORTED',
};

export const TESTSTATUS = {
  PENDING: 'PENDING',
  ONQUE: 'ON-QUE',
  DISPATCHED: 'DISPATCHED',
  CANCELLED: 'CANCELLED',
  VERIFIED: 'VERIFIED',
};

export const PRIORITYSTATUS = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};
// SAMPLETYPE:["BLOOD", "URINE", "STOOL", "SPUTUM", "CSF", "OTHER"]
export const SAMPLETYPE = {
  BLOOD: 'BLOOD',
  URINE: 'URINE',
  STOOL: 'STOOL',
  SPUTUM: 'SPUTUM',
  CSF: 'CSF',
  OTHER: 'OTHER',
};
// TESTSTATUS:["PENDING", "ON-QUE", "DISPATCHED", "CANCELLED", "VERIFIED"]
export const TESTREPORTSTATUS = {
  PENDING: 'PENDING',
  ONQUE: 'ON-QUE',
  DISPATCHED: 'DISPATCHED',
  CANCELLED: 'CANCELLED',
  VERIFIED: 'VERIFIED',
  PUBLISHED: 'PUBLISHED',
};
// STOCKENUM : [
//   "IN-STOCK",
//   "OUT-STOCK",
//   "LOW-STOCK",
// ],
export const STOCKENUM = {
  IN_STOCK: 'IN-STOCK',
  OUT_STOCK: 'OUT-STOCK',
  LOW_STOCK: 'LOW-STOCK',
};

export const CERTIFICATETYPE = {
  BIRTH: 'BIRTH',
  DEATH: 'DEATH',
  DISABILITY: 'DISABILITY',
  MEDICOLEGAL: 'MEDICOLEGAL',
};
